In [1]:
#numpy基础属性

import numpy as np

array  = np.array([[1,2,3],[2,3,4]])  # array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0) -> Create an array.

print(array)

#维数，形状-几行几列，大小
print(array.ndim, array.shape, array.size)


[[1 2 3]
 [2 3 4]]
2 (2, 3) 6


In [2]:
a = np.array([2,23,4],dtype=np.float32) #类型精确 可以减小内存占用
print(a.dtype)

float32


In [3]:
a = np.zeros((3,4))  # zeros(shape, dtype=float, order='C') -> Return a new array of given shape and type, filled with zeros.
print(a, a.dtype)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] float64


In [3]:
a = np.ones((3,4), dtype=np.int16)  # Return a new array of given shape and type, filled with ones.
print(a, a.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int16


In [5]:
a = np.empty((3,4))  # empty(shape, dtype=float, order='C') -> Return a new array of given shape and type, without initializing entries.
print(a, a.dtype)

[[  2.68156159e+154   4.33122285e-311   2.96439388e-323   0.00000000e+000]
 [  2.12199579e-314   4.47032019e-038   7.48611375e-091   1.69175750e-052]
 [  4.31935833e-038   2.72687356e-056   3.99910963e+252   8.34402697e-309]] float64


In [6]:
a = np.arange(10,20,2)  # arange([start,] stop[, step,], dtype=None) -> Return evenly spaced values within a given interval.
print(a)

[10 12 14 16 18]


In [7]:
a = np.arange(12).reshape((3,4))  # reshape() -> Gives a new shape to an array without changing its data.
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
a = np.linspace(1, 20, 20).reshape((4, 5)) # 等间距
print(a)

[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]
 [ 16.  17.  18.  19.  20.]]


In [21]:
# 基本的运算
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print(a, b)
c = a**2 * np.sin(a)
print(c)

print(a < 25)

[10 20 30 40] [0 1 2 3]
[  -54.40211109   365.17810029  -889.22846168  1192.18105677]
[ True  True False False]


In [11]:
# 矩阵的基本运算
a = np.array([[1, 1], [0, 1]])

b = np.arange(4).reshape((2, 2))  # 重整成2行2列

print(a)
print(b)

print('a * b'.center(40, '-'))
print(a * b) # 逐个相乘

print('矩阵乘法'.center(40, '-'))
print(np.dot(a,b)) # 矩阵乘法  矩阵乘法法则: 左行乘以右列
print(a.dot(b))  # 上面等同于下面的矩阵乘法运算

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
-----------------a * b------------------
[[0 1]
 [0 3]]
------------------矩阵乘法------------------
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [32]:
# 矩阵的基本运算
a = np.random.random((2, 4))  # random() == random_sample(size=None) -> Return random floats in the half-open interval [0.0, 1.0).
print(a)

print(np.sum(a, axis=1))     # numpy.sum() ->  Sum of array elements over a given axis.  # axis: 坐标轴
print(np.min(a, axis=0))     # numpy.min() -> Return the minimum of an array or minimum along an axis.
                             # axis=0 表示纵轴， axis=1  表示横轴

[[ 0.06890363  0.73578109  0.39092708  0.90929877]
 [ 0.73815665  0.42756335  0.31625096  0.87633901]]
[ 2.10491057  2.35830996]
[ 0.06890363  0.42756335  0.31625096  0.87633901]


In [45]:
# 矩阵的基本运算
a = np.arange(2, 14).reshape((3, 4))   # 产生一个2到14之间 且3行4列的矩阵
print(a)

print('最小值索引'.center(40, '-'))
print(np.argmin(a)) # 最小值索引
print('最大值索引'.center(40, '-'))
print(np.argmax(a)) 

print('平均值'.center(40, '-'))
print(np.mean(a), a.mean()) # 平均值
print('矩阵纵轴的平均值'.center(40, '-'))
print(np.mean(a, axis=0))

print('加权平均值'.center(40, '-'))
print(np.average(a)) 
print('矩阵的中位数'.center(40, '-'))
print( np.median(a)) #中位数
print('累加 2  2+3 2+3+4 2+3+4+5'.center(40, '-'))
print( np.cumsum(a)) # 累加 2  2+3 2+3+4 2+3+4+5 
print('累差 3-2 4-3 5-4'.center(40, '-'))
print( np.diff(a)) # 累差 3-2 4-3 5-4

a[2][3]=0
print('输出非0'.center(40, '-'))
print(np.nonzero(a)) # 输出非零

print('打印a'.center(40, '-'))
print(a)

print('矩阵排序'.center(40, '-'))
print(np.sort(a)) # 排序

print('矩阵转置'.center(40, '-'))
print(np.transpose(a)) #矩阵转置

print('矩阵乘法'.center(40, '-'))
print(a.T.dot(a))   # a.T -> return array(a) 表示返回一个矩阵转置

print('矩阵值替换 所有小于5的 变为5  大于9的 变为9'.center(40, '-'))
print(np.clip(a,5,9)) #所有小于5的 变为5  大于9的 变为9

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
-----------------最小值索引------------------
0
-----------------最大值索引------------------
11
------------------平均值-------------------
7.5 7.5
----------------矩阵纵轴的平均值----------------
[ 6.  7.  8.  9.]
7.5
-----------------矩阵的中位数-----------------
7.5
--------累加 2  2+3 2+3+4 2+3+4+5---------
[ 2  5  9 14 20 27 35 44 54 65 77 90]
-------------累差 3-2 4-3 5-4-------------
[[1 1 1]
 [1 1 1]
 [1 1 1]]
------------------输出非0------------------
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2]))
------------------打印a-------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12  0]]
------------------矩阵排序------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [ 0 10 11 12]]
------------------矩阵转置------------------
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9  0]]
------------------矩阵乘法------------------
[[140 158 176  64]
 [158 179 200  78]
 [176 200 224  92]
 [ 64  78  92 106]]
-------矩阵值替换 所有小于5的 变为5  大于9的 变为9-------
[[5 5 5 5]
 [

In [49]:
# numpy索引
a = np.arange(3, 15).reshape((3, 4))

print('打印a'.center(40, '-'))
print(a)
print(''.center(40, '-'))
print(a[2][1])
print(a[2,1])
print(a[2,:])
print(a[:,1])

print('逐行打印'.center(40, '-'))
for row in a: # 行
    print(row)

print('逐列打印'.center(40, '-'))
for column in a.T: # 列
    print(column)

print('单个元素打印'.center(40, '-'))
for item in a.flat: # 单个元素
    print(item)

------------------打印a-------------------
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
----------------------------------------
12
12
[11 12 13 14]
[ 4  8 12]
------------------逐行打印------------------
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
------------------逐列打印------------------
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
-----------------单个元素打印-----------------
3
4
5
6
7
8
9
10
11
12
13
14


In [51]:
# 矩阵的合并
a = np.array([1,1,1])
b = np.array([2,2,2])

print('行合并'.center(40, '-'))
print(np.vstack((a,b))) # 行合并

print('列合并'.center(40, '-'))
print(np.hstack((a,b))) # 列合并

print('增加一个维度'.center(40, '-'))
print(a[:, np.newaxis].shape) # 增加一个维度

print('指定维度合并'.center(40, '-'))
c = np.concatenate((a, b, b), axis=0)  # 指定维度的合并
print(c)

------------------行合并-------------------
[[1 1 1]
 [2 2 2]]
------------------列合并-------------------
[1 1 1 2 2 2]
-----------------增加一个维度-----------------
(3, 1)
-----------------指定维度合并-----------------
[1 1 1 2 2 2 2 2 2]


In [56]:
# 矩阵的拆分
a = np.arange(12).reshape((3, 4))

print('打印a'.center(40, '-'))
print(a)

print('横向拆分a, 2表示拆分为2个array'.center(40, '-'))
print(np.split(a, 2, axis=1))    # numpy.split() -> Split an array into multiple sub-arrays.

print('横向拆分a, 3表示拆分为3个array'.center(40, '-'))
print(np.array_split(a, 3, axis=1)) 

print('水平拆分为3个array'.center(40, '-'))
print(np.vsplit(a, 3))

print('垂直拆分为2个array'.center(40, '-'))
print(np.hsplit(a, 2))

------------------打印a-------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------横向拆分a, 2表示拆分为2个array----------
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
----------横向拆分a, 3表示拆分为3个array----------
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
--------------水平拆分为3个array--------------
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
--------------垂直拆分为2个array--------------
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [105]:
# 矩阵的copy
a = np.arange(4)
print(a)

b = a

a[0]=11

b is a

print(b)


d = a.copy()

a[0]=0

print(a)
print(d)



[0 1 2 3]
[11  1  2  3]
[0 1 2 3]
[11  1  2  3]
