# 创建ndarray
创建数组最简单的方法就是用array函数.它接收一切序列型的对象(包括其他数组), 然后产生一个新的含有传入数据的numpy数组

In [1]:
import numpy as np

ndarray_1 = np.array([1, 2, 3, 4])
ndarray_2 = np.array(list('abcdefg'))
ndarray_3 = np.array([[11, 22, 33, 44], [10, 20, 30, 40]])

In [3]:
ndarray_1

array([1, 2, 3, 4])

In [4]:
ndarray_2

array(['a', 'b', 'c', 'd', 'e', 'f', 'g'],
      dtype='<U1')

In [5]:
ndarray_3

array([[11, 22, 33, 44],
       [10, 20, 30, 40]])

## 利用zeros和zeros_like创建数组
用于创建数组，数组元素默认值是0. 注意:zeros_linke函数只是根据传入的ndarray数组的shape来创建所有元素为0的数组，并不是拷贝源数组中的数据.

In [6]:
ndarray4 = np.zeros(10)
ndarray5 = np.zeros((3, 3))
ndarray6 = np.zeros_like(ndarray5)  # 按照 ndarray5 的shape创建数组
# 打印数组元素类型
print("以下为数组类型:")
print('ndarray4:', type(ndarray4))
print('ndarray5:', type(ndarray5))
print('ndarray6:', type(ndarray6))
print("-------------")
print("以下为数组元素类型:")
print('ndarray4:', ndarray4.dtype)
print('ndarray5:', ndarray5.dtype)
print('ndarray6:', ndarray6.dtype)
print("-------------")
print("以下为数组形状:")
print('ndarray4:', ndarray4.shape)
print('ndarray5:', ndarray5.shape)
print('ndarray6:', ndarray6.shape)

以下为数组类型:
ndarray4: <class 'numpy.ndarray'>
ndarray5: <class 'numpy.ndarray'>
ndarray6: <class 'numpy.ndarray'>
-------------
以下为数组元素类型:
ndarray4: float64
ndarray5: float64
ndarray6: float64
-------------
以下为数组形状:
ndarray4: (10,)
ndarray5: (3, 3)
ndarray6: (3, 3)


## ones和ones_likes创建数组
用于创建所有元素都为1的数组.
ones_like用法同zeros_like用法

In [7]:
# 创建数组，元素默认值是0
ndarray7 = np.ones(10)
ndarray8 = np.ones((3, 3))
# 修改元素的值
ndarray8[0][1] = 999
ndarray9 = np.ones_like(ndarray5)  # 按照 ndarray5 的shape创建数组

In [8]:
ndarray7

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
ndarray8

array([[   1.,  999.,    1.],
       [   1.,    1.,    1.],
       [   1.,    1.,    1.]])

In [10]:
ndarray9

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

## empty和empty_like创建数组
用于创建空数组, 空数据中的值并不为0, 而是未初始化的随机值

In [11]:
ndarray10 = np.empty(5)
ndarray11 = np.empty((2, 3))
ndarray12 = np.empty_like(ndarray11)

In [12]:
ndarray10

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
ndarray11

array([[  1.72723371e-077,   2.00390412e+000,   1.48219694e-323],
       [  0.00000000e+000,   0.00000000e+000,   4.17201348e-309]])

In [14]:
ndarray12

array([[  1.72723371e-077,   2.68679615e+154,   1.48219694e-323],
       [  0.00000000e+000,   0.00000000e+000,   4.17201348e-309]])

## arange创建数组
arange函数是python内置函数range函数的数组版本

In [15]:
# 产生0-9共10个元素
ndarray13 = np.arange(10)
# 产生从10-19共10个元素
ndarray14 = np.arange(10, 20)
# 产生10 12 14 16 18, 2为step
ndarray15 = np.arange(10, 20, 2)
# ndarray15的形状
print('ndarray14的形状:', ndarray14.shape)
# 将其形状改变为(2, 5)
ndarray14.reshape((2, 5))

ndarray14的形状: (10,)


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
ndarray13

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
ndarray14

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
ndarray15

array([10, 12, 14, 16, 18])

## eye创建对角矩阵数组
该函数用于创建一个N*N的矩阵, 对角线为1, 其余为0

In [19]:
ndarray16 = np.eye(5)

In [21]:
ndarray16

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])