# 数据类型
我们可以通过ndarray得dtype来打印数组中元素的类型.ndarray常见的数据类型如下:

|类型|类型代码| 说明 |
|-|-|-|
|int8、uint8|i1、u1|有符号和无符号的8位(1个字节长度)整型|
|int16、uint16|i2、u2|有符号和无符号的16位(2个字节长度)整型|
|int32、uint32|i4、u4|有符号和无符号的32位(4个字节长度)整型|
|float16|f2|半精度浮点数|
|float32|f4或f|标准单精度浮点数|
|float64|f8或d|双精度浮点数|
|bool|?|布尔类型|
|object|O|Python对象类型|
|unicode_|U|固定长度的unicode类型，跟字符串定义方式一样|

In [1]:
import numpy as np

ndarray1 = np.array([1, 2, 3, 4])
ndarray2 = np.array(list('abcdefg'))
ndarray3 = np.array([True, False, False, True])
class Person(object):
    pass
ndarray4 = np.array([Person(), Person(), Person()])

In [2]:
ndarray1.dtype

dtype('int64')

In [3]:
ndarray2.dtype

dtype('<U1')

In [4]:
ndarray3.dtype

dtype('bool')

In [5]:
ndarray4.dtype

dtype('O')

## 使用astype函数转换数组类型

In [6]:
ndarray5 = np.array([1, 2, 3, 4, 5])
# 类型转换完毕返回新的数组
ndarray6 = ndarray5.astype(np.float32)

# 如果浮点数转换为整数，则小数部分将会被截断
ndarray7 = np.array([1.1, 2.2, 3.3, 4.4])
ndarray8 = ndarray7.astype(np.int32)

# 如果某些字符串数组表示的全是数字，也可以用astype将其转换为数值类型
ndarray9 = np.array(['10', '20', '30', '40'])
ndarray10 = ndarray9.astype(np.int32)

In [7]:
ndarray5.dtype

dtype('int64')

In [8]:
ndarray6.dtype

dtype('float32')

In [10]:
ndarray7

array([ 1.1,  2.2,  3.3,  4.4])

In [11]:
ndarray8

array([1, 2, 3, 4], dtype=int32)

In [12]:
ndarray9

array(['10', '20', '30', '40'],
      dtype='<U2')

In [13]:
ndarray10

array([10, 20, 30, 40], dtype=int32)